window.esdocSearchIndex = [
  [
    "@aureooms/js-tape/src/tape.js~tape",
    "class/src/Tape.js~Tape.html",
    "<span>Tape</span> <span class=\"search-result-import-path\">@aureooms/js-tape/src/Tape.js</span>",
    "class"
  ],
  [
    "@aureooms/js-tape/src/fromreadstream.js~_fromreadstream",
    "function/index.html#static-function-_fromReadStream",
    "<span>_fromReadStream</span> <span class=\"search-result-import-path\">@aureooms/js-tape/src/fromReadStream.js</span>",
    "function"
  ],
  [
    "@aureooms/js-tape/src/split.js~_split",
    "function/index.html#static-function-_split",
    "<span>_split</span> <span class=\"search-result-import-path\">@aureooms/js-tape/src/split.js</span>",
    "function"
  ],
  [
    "@aureooms/js-tape/src/asynciterablechain.js~asynciterablechain",
    "function/index.html#static-function-asyncIterableChain",
    "<span>asyncIterableChain</span> <span class=\"search-result-import-path\">@aureooms/js-tape/src/asyncIterableChain.js</span>",
    "function"
  ],
  [
    "@aureooms/js-tape/src/asynciterablemap.js~asynciterablemap",
    "function/index.html#static-function-asyncIterableMap",
    "<span>asyncIterableMap</span> <span class=\"search-result-import-path\">@aureooms/js-tape/src/asyncIterableMap.js</span>",
    "function"
  ],
  [
    "@aureooms/js-tape/src/asynciterabletoarray.js~asynciterabletoarray",
    "function/index.html#static-function-asyncIterableToArray",
    "<span>asyncIterableToArray</span> <span class=\"search-result-import-path\">@aureooms/js-tape/src/asyncIterableToArray.js</span>",
    "function"
  ],
  [
    "@aureooms/js-tape/src/chain.js~chain",
    "function/index.html#static-function-chain",
    "<span>chain</span> <span class=\"search-result-import-path\">@aureooms/js-tape/src/chain.js</span>",
    "function"
  ],
  [
    "@aureooms/js-tape/src/exhaust.js~exhaust",
    "function/index.html#static-function-exhaust",
    "<span>exhaust</span> <span class=\"search-result-import-path\">@aureooms/js-tape/src/exhaust.js</span>",
    "function"
  ],
  [
    "@aureooms/js-tape/src/fromasynciterable.js~fromasynciterable",
    "function/index.html#static-function-fromAsyncIterable",
    "<span>fromAsyncIterable</span> <span class=\"search-result-import-path\">@aureooms/js-tape/src/fromAsyncIterable.js</span>",
    "function"
  ],
  [
    "@aureooms/js-tape/src/fromcallable.js~fromcallable",
    "function/index.html#static-function-fromCallable",
    "<span>fromCallable</span> <span class=\"search-result-import-path\">@aureooms/js-tape/src/fromCallable.js</span>",
    "function"
  ],
  [
    "@aureooms/js-tape/src/fromiterable.js~fromiterable",
    "function/index.html#static-function-fromIterable",
    "<span>fromIterable</span> <span class=\"search-result-import-path\">@aureooms/js-tape/src/fromIterable.js</span>",
    "function"
  ],
  [
    "@aureooms/js-tape/src/fromiterator.js~fromiterator",
    "function/index.html#static-function-fromIterator",
    "<span>fromIterator</span> <span class=\"search-result-import-path\">@aureooms/js-tape/src/fromIterator.js</span>",
    "function"
  ],
  [
    "@aureooms/js-tape/src/fromreadstream.js~fromreadstream",
    "function/index.html#static-function-fromReadStream",
    "<span>fromReadStream</span> <span class=\"search-result-import-path\">@aureooms/js-tape/src/fromReadStream.js</span>",
    "function"
  ],
  [
    "@aureooms/js-tape/src/ignore.js~ignore",
    "function/index.html#static-function-ignore",
    "<span>ignore</span> <span class=\"search-result-import-path\">@aureooms/js-tape/src/ignore.js</span>",
    "function"
  ],
  [
    "@aureooms/js-tape/src/map.js~map",
    "function/index.html#static-function-map",
    "<span>map</span> <span class=\"search-result-import-path\">@aureooms/js-tape/src/map.js</span>",
    "function"
  ],
  [
    "@aureooms/js-tape/src/skip.js~skip",
    "function/index.html#static-function-skip",
    "<span>skip</span> <span class=\"search-result-import-path\">@aureooms/js-tape/src/skip.js</span>",
    "function"
  ],
  [
    "@aureooms/js-tape/src/split.js~split",
    "function/index.html#static-function-split",
    "<span>split</span> <span class=\"search-result-import-path\">@aureooms/js-tape/src/split.js</span>",
    "function"
  ],
  [
    "@aureooms/js-tape/src/toarray.js~toarray",
    "function/index.html#static-function-toArray",
    "<span>toArray</span> <span class=\"search-result-import-path\">@aureooms/js-tape/src/toArray.js</span>",
    "function"
  ],
  [
    "@aureooms/js-tape/src/toasynccallable.js~toasynccallable",
    "function/index.html#static-function-toAsyncCallable",
    "<span>toAsyncCallable</span> <span class=\"search-result-import-path\">@aureooms/js-tape/src/toAsyncCallable.js</span>",
    "function"
  ],
  [
    "@aureooms/js-tape/src/toasynciterable.js~toasynciterable",
    "function/index.html#static-function-toAsyncIterable",
    "<span>toAsyncIterable</span> <span class=\"search-result-import-path\">@aureooms/js-tape/src/toAsyncIterable.js</span>",
    "function"
  ],
  [
    "@aureooms/js-tape/src/toasynciterator.js~toasynciterator",
    "function/index.html#static-function-toAsyncIterator",
    "<span>toAsyncIterator</span> <span class=\"search-result-import-path\">@aureooms/js-tape/src/toAsyncIterator.js</span>",
    "function"
  ],
  [
    "@aureooms/js-tape/src/tostring.js~tostring",
    "function/index.html#static-function-toString",
    "<span>toString</span> <span class=\"search-result-import-path\">@aureooms/js-tape/src/toString.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/eof.js",
    "file/src/EOF.js.html",
    "src/EOF.js",
    "file"
  ],
  [
    "src/tape.js",
    "file/src/Tape.js.html",
    "src/Tape.js",
    "file"
  ],
  [
    "src/tape.js~tape#[symbol.asynciterator]",
    "class/src/Tape.js~Tape.html#instance-method-[Symbol.asyncIterator]",
    "src/Tape.js~Tape#[Symbol.asyncIterator]",
    "method"
  ],
  [
    "src/tape.js~tape#[symbol.iterator]",
    "class/src/Tape.js~Tape.html#instance-method-[Symbol.iterator]",
    "src/Tape.js~Tape#[Symbol.iterator]",
    "method"
  ],
  [
    "src/tape.js~tape#buffer",
    "class/src/Tape.js~Tape.html#instance-member-buffer",
    "src/Tape.js~Tape#buffer",
    "member"
  ],
  [
    "src/tape.js~tape#callable",
    "class/src/Tape.js~Tape.html#instance-member-callable",
    "src/Tape.js~Tape#callable",
    "member"
  ],
  [
    "src/tape.js~tape#constructor",
    "class/src/Tape.js~Tape.html#instance-constructor-constructor",
    "src/Tape.js~Tape#constructor",
    "method"
  ],
  [
    "src/tape.js~tape#eof",
    "class/src/Tape.js~Tape.html#instance-member-eof",
    "src/Tape.js~Tape#eof",
    "member"
  ],
  [
    "src/tape.js~tape#read",
    "class/src/Tape.js~Tape.html#instance-method-read",
    "src/Tape.js~Tape#read",
    "method"
  ],
  [
    "src/tape.js~tape#skip",
    "class/src/Tape.js~Tape.html#instance-method-skip",
    "src/Tape.js~Tape#skip",
    "method"
  ],
  [
    "src/tape.js~tape#skipmany",
    "class/src/Tape.js~Tape.html#instance-method-skipMany",
    "src/Tape.js~Tape#skipMany",
    "method"
  ],
  [
    "src/tape.js~tape#unread",
    "class/src/Tape.js~Tape.html#instance-method-unread",
    "src/Tape.js~Tape#unread",
    "method"
  ],
  [
    "src/asynciterablechain.js",
    "file/src/asyncIterableChain.js.html",
    "src/asyncIterableChain.js",
    "file"
  ],
  [
    "src/asynciterablemap.js",
    "file/src/asyncIterableMap.js.html",
    "src/asyncIterableMap.js",
    "file"
  ],
  [
    "src/asynciterabletoarray.js",
    "file/src/asyncIterableToArray.js.html",
    "src/asyncIterableToArray.js",
    "file"
  ],
  [
    "src/chain.js",
    "file/src/chain.js.html",
    "src/chain.js",
    "file"
  ],
  [
    "src/exhaust.js",
    "file/src/exhaust.js.html",
    "src/exhaust.js",
    "file"
  ],
  [
    "src/fromarray.js",
    "file/src/fromArray.js.html",
    "src/fromArray.js",
    "file"
  ],
  [
    "src/fromasynciterable.js",
    "file/src/fromAsyncIterable.js.html",
    "src/fromAsyncIterable.js",
    "file"
  ],
  [
    "src/fromcallable.js",
    "file/src/fromCallable.js.html",
    "src/fromCallable.js",
    "file"
  ],
  [
    "src/fromiterable.js",
    "file/src/fromIterable.js.html",
    "src/fromIterable.js",
    "file"
  ],
  [
    "src/fromiterator.js",
    "file/src/fromIterator.js.html",
    "src/fromIterator.js",
    "file"
  ],
  [
    "src/fromreadstream.js",
    "file/src/fromReadStream.js.html",
    "src/fromReadStream.js",
    "file"
  ],
  [
    "src/fromstring.js",
    "file/src/fromString.js.html",
    "src/fromString.js",
    "file"
  ],
  [
    "src/ignore.js",
    "file/src/ignore.js.html",
    "src/ignore.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/map.js",
    "file/src/map.js.html",
    "src/map.js",
    "file"
  ],
  [
    "src/skip.js",
    "file/src/skip.js.html",
    "src/skip.js",
    "file"
  ],
  [
    "src/split.js",
    "file/src/split.js.html",
    "src/split.js",
    "file"
  ],
  [
    "src/toarray.js",
    "file/src/toArray.js.html",
    "src/toArray.js",
    "file"
  ],
  [
    "src/toasynccallable.js",
    "file/src/toAsyncCallable.js.html",
    "src/toAsyncCallable.js",
    "file"
  ],
  [
    "src/toasynciterable.js",
    "file/src/toAsyncIterable.js.html",
    "src/toAsyncIterable.js",
    "file"
  ],
  [
    "src/toasynciterator.js",
    "file/src/toAsyncIterator.js.html",
    "src/toAsyncIterator.js",
    "file"
  ],
  [
    "src/tostring.js",
    "file/src/toString.js.html",
    "src/toString.js",
    "file"
  ]
]