window.esdocSearchIndex = [
  [
    "@aureooms/js-stream/src/eof.js~eof",
    "variable/index.html#static-variable-EOF",
    "<span>EOF</span> <span class=\"search-result-import-path\">@aureooms/js-stream/src/EOF.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-stream/src/from/streamfromcallable.js~streamfromcallable",
    "class/src/from/StreamFromCallable.js~StreamFromCallable.html",
    "<span>StreamFromCallable</span> <span class=\"search-result-import-path\">@aureooms/js-stream/src/from/StreamFromCallable.js</span>",
    "class"
  ],
  [
    "@aureooms/js-stream/src/split.js~_split",
    "function/index.html#static-function-_split",
    "<span>_split</span> <span class=\"search-result-import-path\">@aureooms/js-stream/src/split.js</span>",
    "function"
  ],
  [
    "@aureooms/js-stream/src/chain.js~chain",
    "function/index.html#static-function-chain",
    "<span>chain</span> <span class=\"search-result-import-path\">@aureooms/js-stream/src/chain.js</span>",
    "function"
  ],
  [
    "@aureooms/js-stream/src/exhaust.js~exhaust",
    "function/index.html#static-function-exhaust",
    "<span>exhaust</span> <span class=\"search-result-import-path\">@aureooms/js-stream/src/exhaust.js</span>",
    "function"
  ],
  [
    "@aureooms/js-stream/src/from/fromarray.js~fromarray",
    "variable/index.html#static-variable-fromarray",
    "<span>fromarray</span> <span class=\"search-result-import-path\">@aureooms/js-stream/src/from/fromarray.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-stream/src/from/fromcallable.js~fromcallable",
    "function/index.html#static-function-fromcallable",
    "<span>fromcallable</span> <span class=\"search-result-import-path\">@aureooms/js-stream/src/from/fromcallable.js</span>",
    "function"
  ],
  [
    "@aureooms/js-stream/src/from/fromiterable.js~fromiterable",
    "function/index.html#static-function-fromiterable",
    "<span>fromiterable</span> <span class=\"search-result-import-path\">@aureooms/js-stream/src/from/fromiterable.js</span>",
    "function"
  ],
  [
    "@aureooms/js-stream/src/from/fromiterator.js~fromiterator",
    "function/index.html#static-function-fromiterator",
    "<span>fromiterator</span> <span class=\"search-result-import-path\">@aureooms/js-stream/src/from/fromiterator.js</span>",
    "function"
  ],
  [
    "@aureooms/js-stream/src/from/fromstring.js~fromstring",
    "variable/index.html#static-variable-fromstring",
    "<span>fromstring</span> <span class=\"search-result-import-path\">@aureooms/js-stream/src/from/fromstring.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-stream/src/ignore.js~ignore",
    "function/index.html#static-function-ignore",
    "<span>ignore</span> <span class=\"search-result-import-path\">@aureooms/js-stream/src/ignore.js</span>",
    "function"
  ],
  [
    "@aureooms/js-stream/src/map.js~map",
    "function/index.html#static-function-map",
    "<span>map</span> <span class=\"search-result-import-path\">@aureooms/js-stream/src/map.js</span>",
    "function"
  ],
  [
    "@aureooms/js-stream/src/skip.js~skip",
    "function/index.html#static-function-skip",
    "<span>skip</span> <span class=\"search-result-import-path\">@aureooms/js-stream/src/skip.js</span>",
    "function"
  ],
  [
    "@aureooms/js-stream/src/split.js~split",
    "function/index.html#static-function-split",
    "<span>split</span> <span class=\"search-result-import-path\">@aureooms/js-stream/src/split.js</span>",
    "function"
  ],
  [
    "@aureooms/js-stream/src/to/toarray.js~toarray",
    "function/index.html#static-function-toarray",
    "<span>toarray</span> <span class=\"search-result-import-path\">@aureooms/js-stream/src/to/toarray.js</span>",
    "function"
  ],
  [
    "@aureooms/js-stream/src/to/tocallable.js~tocallable",
    "function/index.html#static-function-tocallable",
    "<span>tocallable</span> <span class=\"search-result-import-path\">@aureooms/js-stream/src/to/tocallable.js</span>",
    "function"
  ],
  [
    "@aureooms/js-stream/src/to/toiterable.js~toiterable",
    "function/index.html#static-function-toiterable",
    "<span>toiterable</span> <span class=\"search-result-import-path\">@aureooms/js-stream/src/to/toiterable.js</span>",
    "function"
  ],
  [
    "@aureooms/js-stream/src/to/toiterator.js~toiterator",
    "function/index.html#static-function-toiterator",
    "<span>toiterator</span> <span class=\"search-result-import-path\">@aureooms/js-stream/src/to/toiterator.js</span>",
    "function"
  ],
  [
    "@aureooms/js-stream/src/to/tostring.js~tostring",
    "function/index.html#static-function-tostring",
    "<span>tostring</span> <span class=\"search-result-import-path\">@aureooms/js-stream/src/to/tostring.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/eof.js",
    "file/src/EOF.js.html",
    "src/EOF.js",
    "file"
  ],
  [
    "src/chain.js",
    "file/src/chain.js.html",
    "src/chain.js",
    "file"
  ],
  [
    "src/exhaust.js",
    "file/src/exhaust.js.html",
    "src/exhaust.js",
    "file"
  ],
  [
    "src/from/streamfromcallable.js",
    "file/src/from/StreamFromCallable.js.html",
    "src/from/StreamFromCallable.js",
    "file"
  ],
  [
    "src/from/streamfromcallable.js~streamfromcallable#buffer",
    "class/src/from/StreamFromCallable.js~StreamFromCallable.html#instance-member-buffer",
    "src/from/StreamFromCallable.js~StreamFromCallable#buffer",
    "member"
  ],
  [
    "src/from/streamfromcallable.js~streamfromcallable#callable",
    "class/src/from/StreamFromCallable.js~StreamFromCallable.html#instance-member-callable",
    "src/from/StreamFromCallable.js~StreamFromCallable#callable",
    "member"
  ],
  [
    "src/from/streamfromcallable.js~streamfromcallable#constructor",
    "class/src/from/StreamFromCallable.js~StreamFromCallable.html#instance-constructor-constructor",
    "src/from/StreamFromCallable.js~StreamFromCallable#constructor",
    "method"
  ],
  [
    "src/from/streamfromcallable.js~streamfromcallable#eof",
    "class/src/from/StreamFromCallable.js~StreamFromCallable.html#instance-member-eof",
    "src/from/StreamFromCallable.js~StreamFromCallable#eof",
    "member"
  ],
  [
    "src/from/streamfromcallable.js~streamfromcallable#read",
    "class/src/from/StreamFromCallable.js~StreamFromCallable.html#instance-method-read",
    "src/from/StreamFromCallable.js~StreamFromCallable#read",
    "method"
  ],
  [
    "src/from/streamfromcallable.js~streamfromcallable#unread",
    "class/src/from/StreamFromCallable.js~StreamFromCallable.html#instance-method-unread",
    "src/from/StreamFromCallable.js~StreamFromCallable#unread",
    "method"
  ],
  [
    "src/from/fromarray.js",
    "file/src/from/fromarray.js.html",
    "src/from/fromarray.js",
    "file"
  ],
  [
    "src/from/fromcallable.js",
    "file/src/from/fromcallable.js.html",
    "src/from/fromcallable.js",
    "file"
  ],
  [
    "src/from/fromiterable.js",
    "file/src/from/fromiterable.js.html",
    "src/from/fromiterable.js",
    "file"
  ],
  [
    "src/from/fromiterator.js",
    "file/src/from/fromiterator.js.html",
    "src/from/fromiterator.js",
    "file"
  ],
  [
    "src/from/fromstring.js",
    "file/src/from/fromstring.js.html",
    "src/from/fromstring.js",
    "file"
  ],
  [
    "src/from/index.js",
    "file/src/from/index.js.html",
    "src/from/index.js",
    "file"
  ],
  [
    "src/ignore.js",
    "file/src/ignore.js.html",
    "src/ignore.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/map.js",
    "file/src/map.js.html",
    "src/map.js",
    "file"
  ],
  [
    "src/skip.js",
    "file/src/skip.js.html",
    "src/skip.js",
    "file"
  ],
  [
    "src/split.js",
    "file/src/split.js.html",
    "src/split.js",
    "file"
  ],
  [
    "src/to/index.js",
    "file/src/to/index.js.html",
    "src/to/index.js",
    "file"
  ],
  [
    "src/to/toarray.js",
    "file/src/to/toarray.js.html",
    "src/to/toarray.js",
    "file"
  ],
  [
    "src/to/tocallable.js",
    "file/src/to/tocallable.js.html",
    "src/to/tocallable.js",
    "file"
  ],
  [
    "src/to/toiterable.js",
    "file/src/to/toiterable.js.html",
    "src/to/toiterable.js",
    "file"
  ],
  [
    "src/to/toiterator.js",
    "file/src/to/toiterator.js.html",
    "src/to/toiterator.js",
    "file"
  ],
  [
    "src/to/tostring.js",
    "file/src/to/tostring.js.html",
    "src/to/tostring.js",
    "file"
  ]
]